### PR TITLE
Newline fix and various tslint rule changes

### PR DESCRIPTION
**Pull request by myitcv**
@vvakame - I've closed #19 and rebased my changes against your recent commits. Would appreciate some feedback on these changes:

* Use `process.(stderr|stdout)` to fix [this issue](https://github.com/vvakame/typescript-formatter/issues/15#issuecomment-127304963)
* Fix references to and use of the `tslint` indent rule (and corresponding config). The rule takes a `[boolean, string]` pair, [like this](https://github.com/palantir/tslint/blob/551f9ca396b2c4b63e80c7b928797ca7646ee9f0/tslint.json#L8). There was an [error in the `tslint` docs](https://github.com/palantir/tslint/pull/545) which has now been fixed
* Introduce `AdditionalFormatOptions` to reference `tslint "no-consecutive-blank-lines"` and `"no-trailing-whitespace"` config options. These are not supported by the core `ts.FormatCodeOptions`. Perform simple regex replaces if these options are set

### CODE REVIEW

**Comment by vvakame** [comment]
it merged. thanks!

**Comment by myitcv** [comment]
@vvakame - thanks

**Comment by myitcv** [comment]
@vvakame - just to check, your various refactors removed the [change for stripping of trailing whitespace](https://github.com/myitcv/typescript-formatter/commit/bb05b98754f0f54d81ed14c2bfbc030fee90084a#diff-13b5b151431c7e7a17f273559ed212d5R113). Was this intentional? I find this to be extremely useful, particularly for the code generated typescript we are working with.

**Comment by vvakame** [comment]
I think remove trailing spaces are default of typescript service.
I added the test code.
do i have a any mistakes?

**Comment by myitcv** [comment]
@vvakame - apologies, my bad. Yes, the TS service does remove trailing whitespaces, but not it seems from "blank" lines (i.e. lines that only contain whitespace) _within_ comments. Whereas my previous regex replace of course just blanket applies a string replace. No changes needed here then.

**Pull request merged**
