### PR TITLE
feat(filesGlob) : add support for filesGlob

### PR DESCRIPTION
**Pull request by ximenean**
Adding support for filesGlob sections in tsconfig.

### CODE REVIEW

**Comment by ximenean** [comment]
fixes #10

**Comment by ximenean** [comment]
I'm not sure why the travis build is still failing as I've added glob to the package.json.

**Comment by vvakame** [comment]
We should re-create npm-shrinkwrap.json.
I'll take a look this PR. please wait.

**Comment by ximenean** [comment]
ah! Missed that. Thanks. I'll wait.

**Comment by vvakame** [comment]
It merged! thanks :+1: 
I make a 1 additional commit that switch glob to glob-expand.

**Pull request merged**
