### PR TITLE
[WIP] Fix trailing newline and JSX formatting

### PR DESCRIPTION
**Pull request by myitcv**
@vvakame - very much a work in progress but these changes work for me.

* Using a nightly build of TypeScript until `v1.6.0` is released (this is a dependency)
* Using the latest version of type definitions from DefinitelyTyped
* Write messages to `process.(stdout|stderr)`

I've no idea how the `npm-shrinkwrap.json` file has so many changes....new to all this `npm` stuff

### CODE REVIEW

**Comment by vvakame** [comment]
@myitcv thanks you for your contributions!
I make a new commit. b9196e98aee8f342cedc928968424b17c8c1b496

**Comment by vvakame** [comment]
please make minimal set pull request for topic.
I use `typescript@latest` for the moment.

**Comment by myitcv** [comment]
@vvakame - thanks for the commit. However for everything to work for `.jsx` we also need to depend on `typescript@next`. Reason being [this change](https://github.com/Microsoft/TypeScript/blob/842a5b70436ade0180afab763aa0d1c600e20742/src/compiler/parser.ts#L663) is [not in `v1.5.3`](https://github.com/Microsoft/TypeScript/blob/v1.5.3/src/compiler/parser.ts#L517-L529)

So maybe the best thing is to create a branch of this project which is dedicated to `v1.6.0` of TypeScript and reference `typescript@next` whilst we develop that?

**Comment by vvakame** [comment]
@myitcv tsfmt uses peer `typescript` compiler likes grunt-ts (https://github.com/TypeStrong/grunt-ts#compiler
If you want to use typescript@next, use it in your project. tsfmt will find it. 
https://gist.github.com/vvakame/9a6459464258c7de63f9#file-package-json-L6
So it does no good?

**Comment by myitcv** [comment]
Do I need to do anything in particular to set the peer `typescript` version, other than specify the version in `package.json`?

Here's a demo of the problem I'm seeing:

https://github.com/myitcv/tsfmt_funniness

```
$ npm install
...
$ ./node_modules/.bin/tsc --version
message TS6029: Version 1.6.0-dev.20150804
$ ./node_modules/.bin/tsc --jsx preserve input.tsx
$ cat input.jsx
function test() {
    return <span>This is a test</span>;
}
$ ./node_modules/.bin/tsfmt input.tsx
function test(): any {
    return <span>This is a test< /span>;
}
```

Notice the bad formatting of `< /span>` again.

`tsfmt` is using `typescript` from `node_modules/typescript-formatter/node_modules/typescript/bin/typescript.js`... which is not the version I have installed:

```
$ sed -n 6538,6548p node_modules/typescript-formatter/node_modules/typescript/bin/typescript.js
        function createSourceFile(fileName, languageVersion) {
            sourceFile = createNode(228 /* SourceFile */, 0);
            sourceFile.pos = 0;
            sourceFile.end = sourceText.length;
            sourceFile.text = sourceText;
            sourceFile.parseDiagnostics = [];
            sourceFile.bindDiagnostics = [];
            sourceFile.languageVersion = languageVersion;
            sourceFile.fileName = ts.normalizePath(fileName);
            sourceFile.flags = ts.fileExtensionIs(sourceFile.fileName, ".d.ts") ? 2048 /* DeclarationFile */ : 0;
        }
```

Does that make sense? 
Am I doing something wrong?

**Comment by vvakame** [comment]
oh, I understand... npm can't flatten dependencies when typescript@next uses.
I consider what to do.

**Comment by myitcv** [comment]
Closing in favour of #24

**Pull request closed without merging**
